name = "basic_pipeline_example"
version = "0.1.0"
description = "Basic Factory pipeline example"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
